- name: Generate cilium inline manifest
  when: taloscfg_use_cilium_cni
  block:
    - name: Render manifest from helm
      vars:
        taloscfg_helm_args: >-
          {% for arg in taloscfg_cilium_helm_args %}
            --set {{ arg }}
          {% endfor %}
      ansible.builtin.command: >-
        helm template
        cilium cilium
        --repo https://helm.cilium.io/
        --version {{ taloscfg_cilium_version }}
        --namespace kube-system
        --set ipam.mode=kubernetes
        --set securityContext.capabilities.ciliumAgent="{CHOWN,KILL,NET_ADMIN,NET_RAW,IPC_LOCK,SYS_ADMIN,SYS_RESOURCE,DAC_OVERRIDE,FOWNER,SETGID,SETUID}"
        --set securityContext.capabilities.cleanCiliumState="{NET_ADMIN,SYS_ADMIN,SYS_RESOURCE}"
        --set cgroup.autoMount.enabled=false
        --set cgroup.hostRoot=/sys/fs/cgroup
        {% if taloscfg_cilium_repace_kubeproxy %}
          --set k8sServiceHost=localhost
          --set k8sServicePort=7445
          --set kubeProxyReplacement=true
        {% else %}
          --set kubeProxyReplacement=false
        {% endif %}
        {{ taloscfg_helm_args }}
      register: taloscfg_cilium_manifest
      changed_when: false

    - name: Write cilium patch
      ansible.builtin.template:
        src: patch-cilium.yaml.j2
        dest: "{{ taloscfg_target_dir }}/patch-cilium.yaml"
        mode: "0755"
