- name: Generate cilium inline manifest
  run_once: true
  block:
    - name: Render manifest from helm
      ansible.builtin.command: >-
        helm template
        cilium cilium
        --repo https://helm.cilium.io/
        --version {{ taloscfg_cilium_version }}
        --namespace kube-system
        --set ipam.mode=kubernetes
        --set securityContext.capabilities.ciliumAgent="{CHOWN,KILL,NET_ADMIN,NET_RAW,IPC_LOCK,SYS_ADMIN,SYS_RESOURCE,DAC_OVERRIDE,FOWNER,SETGID,SETUID}"
        --set securityContext.capabilities.cleanCiliumState="{NET_ADMIN,SYS_ADMIN,SYS_RESOURCE}"
        --set cgroup.autoMount.enabled=false
        --set cgroup.hostRoot=/sys/fs/cgroup
        --set hubble.enabled=false
        --set clustermesh.enabled=false
        --set authentication.mutual.spire.enabled=false
        {% if taloscfg_cilium_replace_kubeproxy %}
          --set k8sServiceHost=localhost
          --set k8sServicePort=7445
          --set kubeProxyReplacement=true
        {% else %}
          --set kubeProxyReplacement=false
        {% endif %}
      register: taloscfg_cilium_manifest
      changed_when: false

    - name: Write cilium patch
      ansible.builtin.template:
        src: patch-cilium.yaml.j2
        dest: "{{ taloscfg_target_dir }}/patch-cilium.yaml"
        mode: "0600"

    - name: Create cli argument
      ansible.builtin.set_fact:
        taloscfg_cilium_arg: "--config-patch-control-plane @{{ taloscfg_target_dir }}/patch-cilium.yaml"
