- name: Generate patch for high availability
  block:
    - name: Render vip patch
      ansible.builtin.template:
        src: patch-vip.yaml.j2
        dest: "{{ taloscfg_target_dir }}/patch-vip.yaml"
        mode: "0600"

    - name: Create cli argument
      ansible.builtin.set_fact:
        taloscfg_vip_arg: "--config-patch-control-plane @{{ taloscfg_target_dir }}/patch-vip.yaml"
