- name: Generate Talos machineconfig
  when: taloscfg_server_group in group_names or taloscfg_worker_group in group_names
  connection: local
  block:
    - name: Ensure generated directory exists
      ansible.builtin.file:
        path: "{{ taloscfg_target_dir }}/{{ taloscfg_cluster_name }}"
        state: directory
        mode: "0700"
      run_once: true

    - name: Write decrypted secrets to a temporary file
      ansible.builtin.copy:
        content: "{{ lookup('ansible.builtin.file', taloscfg_secrets_file) }}"
        dest: "{{ taloscfg_secrets_file_decrypted }}"
        mode: "0600"
      run_once: true
      no_log: true

    - name: Create vip patch
      ansible.builtin.include_tasks: ha.yaml

    - name: Create cilium patch
      ansible.builtin.include_tasks: cilium.yaml

    - name: Render machineconfig
      vars:
        taloscfg_patch_flag: >-
          {% if taloscfg_server_group in group_names %}
            --config-patch-control-plane
          {% else %}
            --config-patch-worker
          {% endif %}
        taloscfg_output_type: >-
          {% if taloscfg_server_group in group_names %}
            --output-types controlplane
          {% else %}
            --output-types worker
          {% endif %}
        taloscfg_patch_args: >-
          {% for patch in taloscfg_common_patches %}
            {{ taloscfg_patch_flag }} @{{ patch }}
          {% endfor %} {% for patch in taloscfg_machine_patches %}
            {{ taloscfg_patch_flag }} @{{ patch }}
          {% endfor %} {% if taloscfg_server_group in group_names %}
            {% for patch in taloscfg_common_server_patches %}
              {{ taloscfg_patch_flag }} @{{ patch }}
            {% endfor %}
          {% else %}
            {% for patch in taloscfg_common_worker_patches %}
              {{ taloscfg_patch_flag }} @{{ patch }}
            {% endfor %}
          {% endif %}
      ansible.builtin.command: >-
        talosctl gen config {{ taloscfg_cluster_name }}
        https://{{ taloscfg_api_endpoint_cidr | ansible.utils.ipaddr('ip') }}:{{ taloscfg_api_endpoint_port }}
        --force
        --with-secrets {{ taloscfg_secrets_file_decrypted }}
        --kubernetes-version {{ taloscfg_kubernetes_version }}
        --talos-version {{ taloscfg_talos_version }}
        --config-patch '[{"op": "add", "path": "/machine/network/hostname", "value": "{{ inventory_hostname }}"}]'
        {{ taloscfg_patch_args }}
        {{ taloscfg_output_type }}
        {{ taloscfg_vip_arg | default("") }}
        {{ taloscfg_cilium_arg | default("") }}
        -o -
      register: talosctl_machineconfig
      changed_when: false
      no_log: true

    - name: Write machineconfig
      ansible.builtin.copy:
        content: "{{ talosctl_machineconfig.stdout }}"
        dest: "{{ taloscfg_target_dir }}/{{ taloscfg_cluster_name }}/{{ inventory_hostname }}.yaml"
        mode: "0600"
      no_log: true

    - name: Render taloscfg
      ansible.builtin.command: >-
        talosctl gen config {{ taloscfg_cluster_name }}
        https://{{ taloscfg_api_endpoint_cidr | ansible.utils.ipaddr('ip') }}:{{ taloscfg_api_endpoint_port }}
        --force
        --with-secrets {{ taloscfg_secrets_file_decrypted }}
        --kubernetes-version {{ taloscfg_kubernetes_version }}
        --talos-version {{ taloscfg_talos_version }}
        --output-types talosconfig
        -o -
      register: talosctl_taloscfg
      changed_when: false
      run_once: true
      no_log: true

    - name: Write taloscfg
      ansible.builtin.copy:
        content: "{{ talosctl_taloscfg.stdout }}"
        dest: "{{ taloscfg_target_dir }}/{{ taloscfg_cluster_name }}/{{ taloscfg_cluster_name }}.yaml"
        mode: "0600"
      run_once: true
      no_log: true
  always:
    - name: Clean up decrypted secrets
      ansible.builtin.file:
        path: "{{ taloscfg_secrets_file_decrypted }}"
        state: absent
      run_once: true

    - name: Clean up generated patches
      ansible.builtin.file:
        path: "{{ taloscfg_target_dir }}/{{ item }}"
        state: absent
      loop:
        - patch-cilium.yaml
        - patch-vip.yaml
      run_once: true
